development:
  database: financial_control
  adapter: postgresql
  username: postgres
  password: ENV['POSTGRESQL_PASSWORD']
  host: localhost
  encoding: utf8

test:
  database: financial_control_test
  adapter: postgresql
  username: postgres
  password: ENV['POSTGRESQL_PASSWORD']
  host: localhost
  encoding: utf8

production:
  database: financial_control
  adapter: postgresql
  username: postgres
  password: ENV['POSTGRESQL_PASSWORD']
  host: localhost
  encoding: utf8
