name: Run RSpec tests
on: [push, pull_request]
jobs:
  build:
    name: Run RSpec tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1
    - name: Install dependencies
      run:
        bundle install
    - name: Run tests
      run: bundle exec rspec