name: Run RSpec tests
on: [push]
jobs:
  build:
    name: Run RSpec tests
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1
    - name: Install dependencies
      run:
        bundle install
    - name: Set up database
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rails db:create db:schema:load
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:1234@localhost:5432/financial_control_test
    - name: Run tests
      run: bundle exec rspec